version: "3.7"

services:
  zookeeper:
    image: bitnami/zookeeper
    restart: always
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    networks:
      - techbanknet
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    restart: always
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    networks:
      - techbanknet
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_LISTENERS=PLAINTEXT://:9092
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  mongo-container:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - "mongodb_data_container:/data/db"
    networks:
      - techbanknet
  mysql-container:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "mysql_data_container:/var/lib/mysql"
    networks:
      - techbanknet
    environment:
      - "MYSQL_ROOT_PASSWORD=techbankRootPsw"
  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      - "ADMINER_DEFAULT_SERVER=mysql-container"
    networks:
      - techbanknet

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
  mongodb_data_container:
    driver: local
  mysql_data_container:
    driver: local

networks:
  techbanknet:
    driver: bridge